[theme]
base = "dark"
primaryColor = "#A78BFA"
backgroundColor = "#0B0917"
secondaryBackgroundColor = "#16132B"
textColor = "#F4F1FF"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
